site:
  title: Takoyaki Notes
  start_page: TuringTako::index.adoc
content:
  sources:
  - url: https://github.com/Tqkoyaki/TuringTako.git
    branches: master
ui:
  bundle:
    url: https://github.com/Tqkoyaki/TakoraUI/raw/master/bundle/ui-bundle.zip
    snapshot: true